export const OPEN_SIDEDRAWER = 'OPEN_SIDEDRAWER';
export const CLOSE_SIDEDRAWER = 'CLOSE_SIDEDRAWER';
export const SET_SCROLL_POSITION = 'SET_SCROLL_POSITION';
export const SHOW_USER_BTN_SPINNER = 'SHOW_USER_BTN_SPINNER';
export const HIDE_USER_BTN_SPINNER = 'HIDE_USER_BTN_SPINNER';

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_CURRENT_USER_FAIL = 'FETCH_CURRENT_USER_FAIL';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const ADD_USERS = 'ADD_USERS';
export const CLEAR_USERS = 'CLEAR_USERS';
