export const PAGE_LOADED = 'PAGE_LOADED';
export const OPEN_SIDEDRAWER = 'OPEN_SIDEDRAWER';
export const CLOSE_SIDEDRAWER = 'CLOSE_SIDEDRAWER';
export const SET_SCROLL_POSITION = 'SET_SCROLL_POSITION';
export const SHOW_USER_BTN_SPINNER = 'SHOW_USER_BTN_SPINNER';
export const HIDE_USER_BTN_SPINNER = 'HIDE_USER_BTN_SPINNER';
export const SHOW_SUCCESS_POPUP = 'SHOW_SUCCESS_POPUP';
export const HIDE_SUCCESS_POPUP = 'HIDE_SUCCESS_POPUP';

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_CURRENT_USER_FAIL = 'FETCH_CURRENT_USER_FAIL';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const ADD_USERS = 'ADD_USERS';
export const CLEAR_USERS = 'CLEAR_USERS';

export const GET_POSITIONS = 'GET_POSITIONS';
export const GET_POSITIONS_START = 'GET_POSITIONS_START';
export const GET_POSITIONS_SUCCESS = 'GET_POSITIONS_SUCCESS';
export const GET_POSITIONS_FAIL = 'GET_POSITIONS_FAIL';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const SIGN_UP_CLEAR = 'SIGN_UP_CLEAR';

export const SET_USERS_VALUES = 'SET_USERS_VALUES';

export const SHOW_COOKIES_POLICY = 'SHOW_COOKIES_POLICY';
export const HIDE_COOKIES_POLICY = 'HIDE_COOKIES_POLICY';

export const START_FORM_LOADING = 'START_FORM_LOADING';
export const SET_FORM_FILLED = 'SET_FORM_FILLED';
export const SET_FORM_UNFILLED = 'SET_FORM_UNFILLED';

export const SHOW_API_ERROR = 'SHOW_API_ERROR';
export const HIDE_API_ERROR = 'HIDE_API_ERROR';
export const SET_API_ERROR = 'SET_API_ERROR';

export const SHOW_POSITIONS_ERROR = 'SHOW_POSITIONS_ERROR';
